PUT http://localhost:80/products/TESTEE?method=TESTE
Content-Type: application/x-www-form-urlencoded

name=Teste&price=10.00&type=2&specific=10

###
GET http://localhost:80/products/?teste=tesssss
Accept: application/json

###
POST http://localhost:80/products
Content-Type: application/x-www-form-urlencoded

sku=TESTEE&name=Teste&price=10.00&type=2&specific=10

###
POST https://scandiweb-back.000webhostapp.com/products/TESTEEE
Content-Type: application/x-www-form-urlencoded

sku=TESTEE&name=Teste&price=10&type=Weight&specific=10

###
GET http://localhost:80/products/GGWP0007?method=DELETE
Content-Type: application/json
